### ISSUE TITLE
retrained model returns random results

### ISSUE THREAD

**Issue by lbozarth** [tommasoc80/HateBERT#1]
Hi,

I have a quick question about the repo. So the models under HateBERT_finetuned_model are running fine. However, the model under the folder retrained_model is returning random results.

**Comment by tommasoc80** [comment]
Hi, 

the folder retrained_model contains the HateBERT model to be fine-tuned on downstream tasks. Could you be more precise about what you did?

**Comment by lbozarth** [comment]
Ah, that makes sense. Thanks! I'm only looking for pretrained model that
doesn't require fine-tuning at the moment.

**Comment by tommasoc80** [comment]
Ok, then you can use all the models in the folder "HateBERT_finetuned_model ". I am closing this issue now.
